baseurl      = "http://localhost"
title        = "My Blog"
languageCode = "en-uk"
theme        = "hello-friend-ng"
enableRobotsTXT = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableEmoji = true


[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "A simple and beautiful website"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true
    
    # Show a global language switcher in the navigation bar
    enableGlobalLanguageMenu = true

    # Metadata mostly used in document's head
    description = "My website"
    keywords = "homepage"
    images = [""]

   [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

    [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

    [[params.social]]
    name = "github"
    url  = "https://github.com/"

    [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

    [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "ML"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "This is swell"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
    # And you can even create generic menu
    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'
